### ISSUE TITLE
Set-up your Kanban board

### ISSUE THREAD

**Issue by ryxtor** [ryxtor/JS-group-capstone-project-Lucas-Omar#21]
## Hello! 👋🏻 

[Link of the repository](https://github.com/ryxtor/JS-group-capstone-project-Lucas-Omar)
[Link to the Kanban board.
](https://github.com/ryxtor/JS-group-capstone-project-Lucas-Omar/projects/1)
We are a group of 2 persons:

@ryxtor 
@omar25ahmed

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @ryxtor and @omar25ahmed,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted an Issue with a link to your repo, whereas you should have a link to your Kanban board itself

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Cathella** [comment]
## 🔥 Status: Approved 🟢

### Hi @ryxtor, @omar25ahmed 👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
